# Generated by Django 5.1.2 on 2025-01-10 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_user_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='name',
            new_name='Topic_name',
        ),
    ]
