# Generated by Django 5.1.2 on 2025-01-14 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_room_privacy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='Passkey',
        ),
        migrations.AddField(
            model_name='room',
            name='Privacy',
            field=models.CharField(choices=[('Private', 'Private'), ('Public', 'Public')], default='Public', max_length=10),
        ),
    ]
