# Generated by Django 5.1.2 on 2025-01-14 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_room_passkey_room_privacy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='Privacy',
        ),
    ]
