# Generated by Django 5.1.2 on 2025-01-14 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_room_privacy'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomPasskey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passkey', models.CharField(blank=True, max_length=15, unique=True)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.room')),
            ],
        ),
    ]
