# Generated by Django 5.1.2 on 2025-01-14 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_roompasskey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roompasskey',
            name='room',
        ),
        migrations.AddField(
            model_name='room',
            name='passkey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.roompasskey'),
        ),
    ]
