# Generated by Django 5.1.2 on 2025-01-14 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_remove_roompasskey_room_room_passkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='passkey',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.roompasskey'),
        ),
    ]
