# Generated by Django 5.1.2 on 2025-01-14 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_room_passkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='passkey',
        ),
        migrations.RemoveField(
            model_name='room',
            name='Privacy',
        ),
        migrations.DeleteModel(
            name='RoomPasskey',
        ),
    ]
